<a href="https://colab.research.google.com/github/Srujanasri6/pandas-practice-/blob/main/week3sd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [5]:
import numpy as np

In [6]:
df=pd.read_csv('/content/annual-enterprise-survey-2023-financial-year-provisional (2).csv')
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2023,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,930995,ANZSIC06 divisions A-S (excluding classes K633...
1,2023,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,821630,ANZSIC06 divisions A-S (excluding classes K633...
2,2023,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,84354,ANZSIC06 divisions A-S (excluding classes K633...
3,2023,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25010,ANZSIC06 divisions A-S (excluding classes K633...
4,2023,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,832964,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
50980,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50981,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50982,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50983,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50984,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [8]:
df.dtypes

Year                            int64
Industry_aggregation_NZSIOC    object
Industry_code_NZSIOC           object
Industry_name_NZSIOC           object
Units                          object
Variable_code                  object
Variable_name                  object
Variable_category              object
Value                          object
Industry_code_ANZSIC06         object
dtype: object

In [11]:
df.nunique()

Year                              11
Industry_aggregation_NZSIOC        3
Industry_code_NZSIOC             139
Industry_name_NZSIOC             119
Units                              3
Variable_code                     39
Variable_name                     41
Variable_category                  3
Value                          13673
Industry_code_ANZSIC06           121
dtype: int64

In [12]:
df.clip()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2023,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,930995,ANZSIC06 divisions A-S (excluding classes K633...
1,2023,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,821630,ANZSIC06 divisions A-S (excluding classes K633...
2,2023,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,84354,ANZSIC06 divisions A-S (excluding classes K633...
3,2023,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25010,ANZSIC06 divisions A-S (excluding classes K633...
4,2023,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,832964,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
50980,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50981,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50982,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50983,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50984,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [14]:
df.nsmallest()

<bound method DataFrame.nsmallest of        Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0      2023                     Level 1                99999
1      2023                     Level 1                99999
2      2023                     Level 1                99999
3      2023                     Level 1                99999
4      2023                     Level 1                99999
...     ...                         ...                  ...
50980  2013                     Level 3                 ZZ11
50981  2013                     Level 3                 ZZ11
50982  2013                     Level 3                 ZZ11
50983  2013                     Level 3                 ZZ11
50984  2013                     Level 3                 ZZ11

             Industry_name_NZSIOC               Units Variable_code  \
0                  All industries  Dollars (millions)           H01
1                  All industries  Dollars (millions)           H04
2                  All industries  Dollars (millions)           H05
3                  All industries  Dollars (millions)           H07
4                  All industries  Dollars (millions)           H08
...                           ...                 ...           ...
50980  Food product manufacturing          Percentage           H37
50981  Food product manufacturing          Percentage           H38
50982  Food product manufacturing          Percentage           H39
50983  Food product manufacturing          Percentage           H40
50984  Food product manufacturing          Percentage           H41

                                         Variable_name      Variable_category  \
0                                         Total income  Financial performance
1      Sales, government funding, grants and subsidies  Financial performance
2                    Interest, dividends and donations  Financial performance
3                                 Non-operating income  Financial performance
4                                    Total expenditure  Financial performance
...                                                ...                    ...
50980                                      Quick ratio       Financial ratios
50981              Margin on sales of goods for resale       Financial ratios
50982                                 Return on equity       Financial ratios
50983                           Return on total assets       Financial ratios
50984                            Liabilities structure       Financial ratios

        Value                             Industry_code_ANZSIC06
0      930995  ANZSIC06 divisions A-S (excluding classes K633...
1      821630  ANZSIC06 divisions A-S (excluding classes K633...
2       84354  ANZSIC06 divisions A-S (excluding classes K633...
3       25010  ANZSIC06 divisions A-S (excluding classes K633...
4      832964  ANZSIC06 divisions A-S (excluding classes K633...
...       ...                                                ...
50980      52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
50981      40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
50982      12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
50983       5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
50984      46  ANZSIC06 groups C111, C112, C113, C114, C115, ...

[50985 rows x 10 columns]>